### ISSUE TITLE
síntesis 

### ISSUE THREAD

**Issue by carlos-chrs** [SistemasTecTlaxiaco/actividad-3-sintesis-carlos-chrs#2]
[Sintesis_CARLOS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-carlos-chrs/files/9447546/Sintesis_CARLOS.pdf)

**Comment by bg55-a** [comment]
Calificación:19%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
