### ISSUE TITLE
SINTESISSSS

### ISSUE THREAD

**Issue by carlos-chrs** [SistemasTecTlaxiaco/actividad-3-sintesis-carlos-chrs#3]

**Comment by carlos-chrs** [comment]
[Sintesis_CARLOS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-carlos-chrs/files/9472882/Sintesis_CARLOS.pdf)

**Comment by josealfredo79** [comment]
Calificacion 18
